const root=document.documentElement,body=document.body;
document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
document.querySelectorAll('img[src="assets/depakar-profile.png"]').forEach(img=>img.alt='Portrait of Depakar B, WordPress Developer');
const header=document.querySelector('.site-header');
if(header){const tools=document.createElement('div');tools.className='utility';tools.innerHTML='<button class="theme-toggle" type="button" aria-label="Switch colour mode">Light</button><select class="language-select" aria-label="Choose website language"><option value="en">EN</option><option value="fr">FR</option><option value="it">IT</option></select>';header.append(tools);const theme=tools.querySelector('.theme-toggle');const saved=localStorage.getItem('theme');if(saved==='light')body.classList.add('light');theme.textContent=body.classList.contains('light')?'Dark':'Light';theme.addEventListener('click',()=>{body.classList.toggle('light');localStorage.setItem('theme',body.classList.contains('light')?'light':'dark');theme.textContent=body.classList.contains('light')?'Dark':'Light';});}
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#site-nav');if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});}
const translations={fr:{available:'Disponible pour certains projets',heroTitle:'Je crée des sites web clairs, rapides et faciles à trouver.',heroIntro:'Développement WordPress, ingénierie de plugins, SEO technique, AEO, GEO et performance — pensés pour de vrais besoins.',whatsapp:'Discuter sur WhatsApp',viewWork:'Voir mes projets',introBand:'Je transforme les idées, les designs et les besoins métier en expériences digitales prêtes pour la production.',selected:'Projets sélectionnés',projectTitle:'Un travail qui a du sens.',allProjects:'Voir tous les projets',capabilities:'Compétences',capabilityTitle:'Au-delà de l’interface.',ctaQuestion:'Un site ou un produit à améliorer ?',ctaButton:'Commencer sur WhatsApp'},it:{available:'Disponibile per progetti selezionati',heroTitle:'Creo siti web chiari, veloci e facili da trovare.',heroIntro:'Sviluppo WordPress, plugin engineering, SEO tecnico, AEO, GEO e performance — per esigenze aziendali reali.',whatsapp:'Scrivi su WhatsApp',viewWork:'Vedi i miei progetti',introBand:'Trasformo idee, design e requisiti aziendali in esperienze digitali pronte per la produzione.',selected:'Progetti selezionati',projectTitle:'Lavoro con uno scopo.',allProjects:'Vedi tutti i progetti',capabilities:'Competenze',capabilityTitle:'Oltre l’interfaccia.',ctaQuestion:'Hai un sito o un prodotto che deve funzionare meglio?',ctaButton:'Inizia su WhatsApp'}};
const english={};document.querySelectorAll('[data-i18n]').forEach(el=>english[el.dataset.i18n]=el.textContent.trim());function translate(lang){root.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;el.textContent=lang==='en'?english[key]:(translations[lang]?.[key]||english[key]);});document.querySelectorAll('#site-nav a').forEach(a=>{const labels={en:{'index.html':'Home','work.html':'Work','about.html':'About','plugins.html':'Plugins','contact.html':'Contact'},fr:{'index.html':'Accueil','work.html':'Projets','about.html':'À propos','plugins.html':'Plugins','contact.html':'Contact'},it:{'index.html':'Home','work.html':'Lavori','about.html':'Chi sono','plugins.html':'Plugin','contact.html':'Contatti'}};const key=a.getAttribute('href');if(labels[lang]?.[key])a.textContent=labels[lang][key];});localStorage.setItem('portfolio-language',lang);}const select=document.querySelector('.language-select');if(select){const saved=localStorage.getItem('portfolio-language')||'en';select.value=saved;translate(saved);select.addEventListener('change',e=>translate(e.target.value));}
const form=document.querySelector('[data-contact-form]');if(form){form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status'),button=form.querySelector('button');if(form.action.includes('YOUR_FORM_ID')){status.textContent='Form delivery is being connected. Please email depakar418@gmail.com for now.';status.className='form-status error';return;}button.disabled=true;button.textContent='Sending…';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error();form.reset();status.textContent='Thanks — your message is on its way.';status.className='form-status success';}catch{status.textContent='That did not send. Please email depakar418@gmail.com instead.';status.className='form-status error';}finally{button.disabled=false;button.textContent='Send enquiry';}});}
